const MATHJAX_CONFIG = {
  Macros: {
    A: '{\\mathbb{A}}',
    B: '{\\mathbb{B}}',
    C: '{\\mathbb{C}}',
    D: '{\\mathbb{D}}',
    E: '{\\mathbb{E}}',
    F: '{\\mathbb{F}}',
    G: '{\\mathbb{G}}',
    H: '{\\mathbb{H}}',
    I: '{\\mathbb{I}}',
    J: '{\\mathbb{J}}',
    K: '{\\mathbb{K}}',
    L: '{\\mathbb{L}}',
    M: '{\\mathbb{M}}',
    N: '{\\mathbb{N}}',
    O: '{\\mathbb{O}}',
    P: '{\\mathbb{P}}',
    Q: '{\\mathbb{Q}}',
    R: '{\\mathbb{R}}',
    S: '{\\mathbb{S}}',
    T: '{\\mathbb{T}}',
    U: '{\\mathbb{U}}',
    V: '{\\mathbb{V}}',
    W: '{\\mathbb{W}}',
    X: '{\\mathbb{X}}',
    Y: '{\\mathbb{Y}}',
    Z: '{\\mathbb{Z}}',
    PP: '{\\mathcal{P}}',
    MM: '{\\mathcal{M}}',
    tolearn: ['\\color{firebrick}{\\ddagger\\tiny{ \\text{ #1 }}}', 1],
    todo: ['{\\color{grey}{\\tiny{\\bigstar \\text{ #1 }}}}', 1],
    msi: '{\\displaystyle}',
    msn: '{\\textstyle}',
    ims: '{\\scriptstyle}',
    iims: '{\\scriptscriptstyle}',
    tsv: '{\\Huge}',
    tsiv: '{\\huge}',
    tsiii: '{\\LARGE}',
    tsii: '{\\Large}',
    tsi: '{\\large}',
    tsn: '{\\normalsize}',
    its: '{\\small}',
    iits: '{\\footnotesize}',
    iiits: '{\\scriptsize}',
    ivts: '{\\tiny}',
    tssf: '{\\textsf}',
    aclosed: [
      '{#1, #2 \\in #3 &\\implies #1 #4 #2 \\in #3}',
      4,
      'a',
      'b',
      '\\F',
      '+'
    ],
    qeda: '{\\blacksquare}',
    qedb: '{\\square}',
    bold: ['{\\bf #1}', 1],
    italic: ['{\\em #1}', 1]
  }
};

export default MATHJAX_CONFIG;
